### ISSUE TITLE
Kernel source for 4.19.122-v7l+ and build.sh parameters

### ISSUE THREAD

**Issue by corteXnzt** [OpenHD/OpenHDKernelBuilder#4]
Hello, I'm trying to install i2s driver on openHD and it requires the kernel source. Can you link me to the file(s)?

![Screenshot from 2021-03-20 20-18-01](https://user-images.githubusercontent.com/49268713/111891668-753d9c00-8a2f-11eb-898d-d2b2260f3c64.png)

If there is non readily available I can try to build but I don't know the parameters to input.
![Screenshot from 2021-03-20 20-37-13](https://user-images.githubusercontent.com/49268713/111891669-77075f80-8a2f-11eb-8a71-c516120d063b.png)

TIA.

**Comment by raphaelscholle** [comment]
I think this issue should be resolved, sorry for the long delay, the current 2.0x kernel is in the 2.0 branch, not in master, 2.0 kernels can be build with ./build.sh pi buster
